[docs] Update python style conventions #122
openwisp/openwisp2-docs pull request #126
Opened 2020-12-30 13:46 UTC by prajwal296

fixes #112

2020-12-30 14:29 UTC, Purhan requested changes
@prajwal296 your commit message is wrong (referencing the wrong issue). Moreover, someone else was already working on this issue.

2020-12-30 18:07 UTC, nemesisdesign requested changes

2020-12-30 18:07 UTC, nemesisdesign commented on developer/contributing.rst
> +- `black <https://black.readthedocs.io/en/stable/>`_ is used to
falke8, isort and black are all used, we need to mention this without mentioning the scripts which are not being used anymore.

2020-12-30 18:07 UTC, nemesisdesign commented on developer/contributing.rst
> +  checks for these code conventions.
Add this after the mention to openwisp-qa-format, please explain that these scripts contain the logic to perform all the QA checks specific to each module

2021-02-05 05:54 UTC, Purhan commented
Seems the issue is closed. Reopen if not.

2021-02-05 05:54 UTC, closed without merging