[ci] Move CI to Github Actions
openwisp/openwisp2-docs pull request #133
Opened 2021-04-02 12:22 UTC by ManishShah120

2021-04-02 12:26 UTC, ManishShah120 commented
@devkapilbansal this is working :+1:

2021-04-03 09:47 UTC, devkapilbansal requested changes
@ManishShah120 just one minor change :point_down:

2021-04-03 09:47 UTC, devkapilbansal commented on .github/workflows/ci.yml
> +          ./run-qa-checks
```suggestion
        run: ./run-qa-checks
```

2021-04-03 11:57 UTC, devkapilbansal approved these changes
LGTM 👍

2021-04-03 20:23 UTC, nemesisdesign approved these changes

2021-04-03 20:23 UTC, merged